const products = [
    {id: '1', name : 'Zapatillas Vans Skate Grosso Mid Navy Orange', description: 'Zapatillas Vans Skate Grosso Mid Navy Orange de chico',  category : 'calzado', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/image/602f0fa2c1f0d1ba5e241f914e856ff9/z/v/zva350-zapatillas-vans-skate-grosso-mid-navy-orange.jpg', price : '19,90'},
    {id: '2', name : 'Cruiser Santa Cruz Classic Wave Splice 8.8 x 27.7', description: 'Cruiser Santa Cruz Classic Wave Splice 8.8 x 27.7 pulgadas.',  category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/image/800x/602f0fa2c1f0d1ba5e241f914e856ff9/c/r/crsanta025-cruiser-santa-cruz-classic-wave-splice-8.8x27.7.jpg', price : '169,90'},
    {id: '3', name : 'Gorro Element Dusk Canyon Khaki', description: 'Gorro Element Dusk Canyon Khaki', category : 'complementos', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/g/e/gel098-gorro-element-dusk-canyon-khaki.jpg', price : '19,90'},
    {id: '4', name : 'Tabla Skate Welcome Triger Dark Lord White Dip 9.75', description: 'Tabla Skate Welcome Triger Dark Lord White Dip 9.75 pulgadas', category : 'skateboarding',  image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/t/w/twel016-tabla-skate-welcome-triger-dark-lord-white-dip-9.75_1.jpg', price : '91,90'},
    {id: '5', name : 'Camiseta Volcom Mindbottle LSE White', description: 'Camiseta Volcom Mindbottle LSE White de chico',  category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/c/v/cvo360-camiseta-volcom-mindbottle-lse-white_1.jpeg', price : '27,92'},
    {id: '6', name : 'Zapatillas Vans Wayvee Tyson Peterson Black Asphalt', description: 'Zapatillas Vans Wayvee Tyson Peterson Black Asphalt de chico.', category : 'calzado', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/z/v/zva351-zapatillas-vans-wayvee-tyson-peterson-black-asphalt.jpg', price : '99,90'},
    {id: '7', name : 'Mochila Vans Realm Flying V Backpack Powder Pink', description: 'Mochila Vans Realm Flying V Backpack Powder Pink', category : 'complementos', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/m/v/mva475-mochila-vans-realm-flying-v-powder-pink.jpg', price : '44,90'},
    {id: '8', name : 'Sudadera HUF Hot Dice Triple Triangle Natural', description: 'Sudadera HUF Hot Dice Triple Triangle Natural', category : 'sudaderas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/667.8x/602f0fa2c1f0d1ba5e241f914e856ff9/s/h/shuf016-sudadera-huf-hot-dice-triple-triangle-natural.jpg', price : '84,90'},
    {id: '9', name : 'Camiseta A Lost Cause Gotcha Again Black', description: 'Camiseta A Lost Cause Gotcha Again Black de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/a/calc006-camiseta-a-lost-cause-gotcha-again-black.jpg', price : '28,72'},
    {id: '10', name : 'Camiseta A Lost Cause Skull Island V2 Raglan White Black', description: 'Camiseta A Lost Cause Skull Island V2 Raglan White Black de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/v/cvo325-camiseta-volcom-pinner-heather-sandstone.jpg', price : '28,72'},
    {id: '11', name : 'Camiseta Obey Eyes Icon 2 Bright Lime', description: 'Camiseta Obey Eyes Icon 2 Bright Lime de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/o/cob043-camiseta-obey-icon-eyes-2-bright-lime.jpg', price : '31,90'},
    {id: '12', name : 'Camiseta The Dudes Unathletics Dept Black', description: 'Camiseta The Dudes Unathletics Dept Black de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/t/ctd008-camiseta-the-dudes-unathletics-dept-black.jpg', price : '28,72'},
    {id: '13', name : 'Camiseta The Dudes Too Short Smokes Black', description: 'Camiseta The Dudes Too Short Smokes Black de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/t/ctd003-camiseta-the-dudes-too-short-smokes-black.jpg', price : '39,90'},
    {id: '14', name : 'Camiseta Santa Cruz Opus Dot Stripe Black', description: 'Camiseta Santa Cruz Opus Dot Stripe Black de chico', category : 'camisetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/c/s/csanta106-camiseta-santa-cruz-opus-dot-stripe-black.jpg', price : '32,90'},
    {id: '15', name : 'Sudadera Vans Flying V FT Boxy Black', description: 'Sudadera Vans Flying V FT Boxy Black de chica', category : 'sudaderas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/s/v/sva069-sudadera-vans-flying-v-ft-boxy-black.jpg', price : '64,90'},
    {id: '16', name : 'Sudadera Santa Cruz Lucky Cat Black', description: 'Sudadera Santa Cruz Lucky Cat Black de chica', category : 'sudaderas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/s/s/ssanta038-sudadera-santa-cruz-lucky-cat-black.jpg', price : '64,90'},
    {id: '17', name : 'Sudadera Santa Cruz Heart Dot Check Crew Sea Blue', description: 'Sudadera Santa Cruz Heart Dot Check Crew Sea Blue de chica', category : 'sudaderas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/s/s/ssanta074-sudadera-santa-cruz-heart-dot-check-crew-sea-blue.jpg', price : '64,90'},
    {id: '18', name : 'Jersey Santa Cruz Checkerbloom Knit Black', description: 'Jersey Santa Cruz Checkerbloom Knit Black de chica', category : 'sudaderas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/s/s/ssanta075-jersey-santa-cruz-checkerbloom-knit-black.jpg', price : '69,90'},
    {id: '19', name : 'Tabla Skate Element X Star Wars Mandalorian Hunter & Prey 8.0 + Lija', description: 'Tabla Skate Element X Star Wars Mandalorian Hunter & Prey 8.0 pulgadas + lija', category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/t/e/tel360-tabla-skate-element-x-star-wars-mandalorian-hunter-_-prey-8.0.jpg', price : '69,00'},
    {id: '20', name : 'Tabla Skate Enjoi Whitey Panda Logo Wide R7 8.5 + Lija', description: 'Tabla Skate Enjoi Whitey Panda Logo Wide R7 8.5 pulgadas + lija gratis', category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/t/e/ten016-tabla-skate-enjoi-whitey-panda-logo-wide-r7_5.jpg', price : '59,90'},
    {id: '21', name : 'Tabla Skate Cruzade Army Label Yellow 8.875 + Lija', description: 'Tabla Skate Cruzade Army Label Yellow 8.875 pulgadas + lija', category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/t/c/tcrz029-tabla-skate-cruzade-army-label-yellow-8.875.jpg', price : '59,90'},
    {id: '22', name : 'Tabla Skate Jart Renaissance II Santa Maria 8.25 + Lija', description: 'Tabla Skate Jart Renaissance II Santa Maria 8.25 pulgadas + lija', category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/t/j/tja259-tabla-skate-jart-renaissance-ii-santa-maria-8.25.jpg', price : '49,90'},
    {id: '23', name : 'Tabla Skate Toy Machine Provost Fountain 8.13 + Lija', description: 'Tabla Skate Toy Machine Provost Fountain 8.13 pulgadas + lija', category : 'skateboarding', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/t/t/ttm022-tabla-skate-toy-machine-provost-fountain-8.13.jpg', price : '57,51'},
    {id: '24', name : 'Zapatillas Globe Tilt Wheat Black Winter', description: 'Zapatillas Globe Tilt Wheat Black Winter marrones con suela negra de chico', category : 'calzado', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/1000x/602f0fa2c1f0d1ba5e241f914e856ff9/z/g/zgl044-zapatillas-globe-tilt-wheat-black-winter.jpg', price : '84,90'},
    {id: '25', name : 'Zapatillas Vans Slip-On Pro Checkerboard Black White', description: 'Zapatillas Vans Slip-On Pro Checkerboard Black White blancas con cuadraditos negros', category : 'calzado', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/z/v/zva300-zapatillas-vans-slip-on-pro-checkerboard-black-white.jpg', price : '59,90'},
    {id: '26', name : 'Chaqueta Vans Embers Checkerboard', description: 'Chaqueta Vans Embers Checkerboard de chica', category : 'chaquetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/c/h/chva006-chaqueta-vans-embers-checkerboard_1.jpg', price : '109,90'},
    {id: '27', name : 'Chaqueta Parka Grimey Sighting In Vostok White', description: 'Chaqueta Parka Grimey Sighting In Vostok White de chico y chica', category : 'chaquetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/c/h/chgry021-chaqueta-parka-grimey-sighting-in-vostok-white.jpg', price : '119,90'},
    {id: '28', name : 'Chubasquero Grimey Strange Fruit Raincoat Purple', description: 'Chubasquero Grimey Strange Fruit Raincoat Purple', category : 'chaquetas', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/c/h/chgry036-chubasquero-grimey-strange-fruit-purple.jpg', price : '74,90'},
    {id: '29', name : 'Pantalones Volcom Frickin Slim Jogger Desert Taupe', description: 'Pantalones Volcom Frickin Slim Jogger Desert Taupe de chico', category : 'pantalones', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/p/a/pavo133-pantalon-volcom-frickin-slim-jogger-desert-taupe.jpg', price : '69,90'},
    {id: '30', name : 'Leggings Vans Chalkboard Classic Black White', description: 'Leggings Vans Chalkboard Classic Black White de chica', category : 'pantalones', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/p/a/pava004-leggings-vans-chalkboard-black-white.jpg', price : '27,92 '},
    {id: '31', name : 'Pantalones Volcom Frochick Travel Black', description: 'Pantalones Volcom Frochick Travel Black de chica', category : 'pantalones', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/p/a/pavo132-pantalon-volcom-frochick-travel-black.jpg', price : '55,92'},
    {id: '32', name : 'Pantalones Volcom Denim Jogger Black', description: 'Pantalones Volcom Denim Jogger Black de chico', category : 'pantalones', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/p/a/pavo131-pantalon-volcom-denim-jogger-black.jpg', price : '74,90'},
    {id: '33', name : 'Gorro Bucket Obey Bold Black', description: 'Gorro Bucket Obey Bold Black', category : 'complementos', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/g/o/gob043-gorro-bucket-obey-bold-black.jpg', price : '35,90'},
    {id: '34', name : 'Gorra Vans Classic Patch White Black', description: 'Gorra Vans Classic Patch White Black', category : 'complementos', image : 'https://cdn.skatespain.com/media/catalog/product/cache/1/small_image/500x/602f0fa2c1f0d1ba5e241f914e856ff9/g/v/gva020-gorra-vans-classic-patch-true-white-black.jpg', price : '24,90'}
    
]

export const getData = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve(products)
    }, 4000)
})
